# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lennard Goh
tagline:          Personal Page
url:              http://lennardgoh.github.io
paginate:         1
baseurl:          /
author:
  name:           Lennard Goh
  url:            https://twitter.com/lennardgoh
  email:          lennardgoh@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lennardgoh/lennardgoh.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
About: '/about/'
Archive: '/archive/'
