# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lennard Goh
tagline:          Personal Page
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lennardgoh.github.io

author:
  name:           'Lennard Goh'
  url:            https://twitter.com/lennardgoh

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lennardgoh/lennardgoh.github.io
